/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ResetPasswordImport } from './routes/reset-password'
import { Route as RecoverPasswordImport } from './routes/recover-password'
import { Route as LoginImport } from './routes/login'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutSettingsImport } from './routes/_layout/settings'
import { Route as LayoutItemsImport } from './routes/_layout/items'
import { Route as LayoutAdminImport } from './routes/_layout/admin'
import { Route as LayoutStoreProductsImport } from './routes/_layout/store/products'
import { Route as LayoutStoreIndexImport } from './routes/_layout/store/index'
import { Route as LayoutPostsIndexImport } from './routes/_layout/posts.index'
import { Route as LayoutNotificationIndexImport } from './routes/_layout/notification.index'
import { Route as LayoutStoreCustomersImport } from './routes/_layout/store/customers'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ResetPasswordRoute = ResetPasswordImport.update({
  path: '/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const RecoverPasswordRoute = RecoverPasswordImport.update({
  path: '/recover-password',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutSettingsRoute = LayoutSettingsImport.update({
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutItemsRoute = LayoutItemsImport.update({
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutAdminRoute = LayoutAdminImport.update({
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoreProductsRoute = LayoutStoreProductsImport.update({
  path: '/store/products',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoreIndexRoute = LayoutStoreIndexImport.update({
  path: '/store/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutPostsIndexRoute = LayoutPostsIndexImport.update({
  path: '/posts/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutNotificationIndexRoute = LayoutNotificationIndexImport.update({
  path: '/notification/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutStoreCustomersRoute = LayoutStoreCustomersImport.update({
  path: '/store/customers',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/recover-password': {
      preLoaderRoute: typeof RecoverPasswordImport
      parentRoute: typeof rootRoute
    }
    '/reset-password': {
      preLoaderRoute: typeof ResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_layout/admin': {
      preLoaderRoute: typeof LayoutAdminImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/items': {
      preLoaderRoute: typeof LayoutItemsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/settings': {
      preLoaderRoute: typeof LayoutSettingsImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/': {
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/store/customers': {
      preLoaderRoute: typeof LayoutStoreCustomersImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/notification/': {
      preLoaderRoute: typeof LayoutNotificationIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/posts/': {
      preLoaderRoute: typeof LayoutPostsIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/store/': {
      preLoaderRoute: typeof LayoutStoreIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/store/products': {
      preLoaderRoute: typeof LayoutStoreProductsImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  LayoutRoute.addChildren([
    LayoutAdminRoute,
    LayoutItemsRoute,
    LayoutSettingsRoute,
    LayoutIndexRoute,
    LayoutStoreCustomersRoute,
    LayoutNotificationIndexRoute,
    LayoutPostsIndexRoute,
    LayoutStoreIndexRoute,
    LayoutStoreProductsRoute,
  ]),
  LoginRoute,
  RecoverPasswordRoute,
  ResetPasswordRoute,
  SignupRoute,
])

/* prettier-ignore-end */
