name: Labels

on:
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    triage:
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
        -   name: Apply labels using labeler
            uses: actions/labeler@v5
